### ISSUE TITLE
tensorflow=2.10.0 to 2.11.1 are incompatible with latest keras-tuner=1.3.4 (python 3.10) [protobuf version limit]

### ISSUE THREAD

**Issue by sh-shahrokhi** [conda-forge/keras-tuner-feedstock#21]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hello,
I tried to install `keras-tuner=1.3.4` with `tensorflow=2.10` to `tensorflow=2.11.1` in linux-64 with `python=3.10.`
They are incompatible and the order of installation does not no matter.
`tensorflow=2.9.1` works with python=3.10.8

install commands:

✓ `mamba install tensorflow=2.9.1 keras-tuner=1.3.4 -c conda-forge` (python=3.10.8)

✕ `mamba install tensorflow=2.10 keras-tuner=1.3.4 -c conda-forge`
✕ `mamba install tensorflow=2.11.0 keras-tuner=1.3.4 -c conda-forge`
✕ `mamba install tensorflow=2.11.1 keras-tuner=1.3.4 -c conda-forge`

Error outputs:

```
└─ tensorflow 2.10**  is installable with the potential options
   ├─ tensorflow 2.10.0 would require
   │  └─ tensorflow-base 2.10.0 cpu_py310hc537a0e_0, which requires
   │     └─ libprotobuf >=3.21.6,<3.22.0a0 , which conflicts with any installable versions previously reported;
```
```
└─ tensorflow 2.11.0**  is installable with the potential options
   ├─ tensorflow 2.11.0 would require
   │  └─ tensorflow-base [2.11.0 cpu_py310*_0|2.11.0 cuda112py310*_0], which requires
   │     └─ libprotobuf >=3.21.11,<3.22.0a0 , which conflicts with any installable versions previously reported;

```
```
└─ tensorflow 2.11.1**  is installable with the potential options
   ├─ tensorflow 2.11.1 would require
   │  └─ tensorflow-base [2.11.1 cpu_py310h335d60c_0|2.11.1 cuda112py310h4c92a00_0], which requires
   │     └─ libprotobuf >=3.21.12,<3.22.0a0 , which conflicts with any installable versions previously reported;

```
---

`keras-tuner=1.3.4` on `python 3.10 ` requires` protobuf=3.20.3` which requiers  `libprotobuf=3.20.3`. They are all available on `conda-forge`.

### Installed packages

```shell
# packages in environment at /home/me/software/mambaforge/envs/img:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.1.0                h0b41bf4_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
python                    3.10.10         he550d4f_0_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : img
    active env location : /home/me/software/mambaforge/envs/img
            shell level : 10
       user config file : /home/me/.condarc
 populated config files : /home/me/software/mambaforge/.condarc
                          /home/me/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.37=0
                          __linux=5.15.90.1=0
                          __unix=0=0
       base environment : /home/me/software/mambaforge  (writable)
      conda av data dir : /home/me/software/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/me/software/mambaforge/pkgs
                          /home/me/.conda/pkgs
       envs directories : /home/me/software/mambaforge/envs
                          /home/me/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Linux/5.15.90.1-microsoft-standard-WSL2 opensuse-tumbleweed/20230407 glibc/2.37
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
issue transfered to `keras-tuner` feedstock since it seems that the constraint is coming from here.

**Comment by h-vetinari** [comment]
The limit here is wrong. Or perhaps only "wrong", as in: not suitable for what we do in conda-forge (using shared libraries, of which there can only be one per environment, which therefore needs to match for all packages, which means those packages need to be migrated for each new version as we do).

We need to remove it (perhaps even patch the source), because it is unworkable with all of the above.

This is against a common rule ("reflect upstream dependency constraints accurately"), but protobuf is special. Its ABI impact (combined with PyPI's lack of infrastructure & metadata for distributing non-python artefacts) makes many projects very defensive to changing anything about the protobuf version, and will pin hard to the latest one they've tested.

Despite protobuf's versioning shenanigans, their API is actually very stable and once one can handle the recompilation aspect for new protobuf minor versions (as we do), it's a non-issue to raise that bound.

**Comment by sh-shahrokhi** [comment]
> The limit here is wrong. Or perhaps only "wrong", as in: not suitable for what we do in conda-forge (using shared libraries, of which there can only be one per environment, which therefore needs to match for all packages, which means those packages need to be migrated for each new version as we do).
> 
> We need to remove it (perhaps even patch the source), because it is unworkable with all of the above.
> 
> This is against a common rule ("reflect upstream dependency constraints accurately"), but protobuf is special. Its ABI impact (combined with PyPI's lack of infrastructure & metadata for distributing non-python artefacts) makes many projects very defensive to changing anything about the protobuf version, and will pin hard to the latest one they've tested.
> 
> Despite protobuf's versioning shenanigans, their API is actually very stable and once one can handle the recompilation aspect for new protobuf minor versions (as we do), it's a non-issue to raise that bound.

FYI, here is a pull request on upstream, which removes the limit on protobuf.
https://github.com/keras-team/keras-tuner/pull/892

**Comment by h-vetinari** [comment]
Upstream may not want to remove it (because they care about distribution on PyPI, where this can go wrong). Of course, upstream changes are better (no patches), but I wouldn't be surprised if they reject this, and then we should still change it, but only on the feedstock.

**Comment by haifeng-jin** [comment]
KerasTuner will not be compatible with TF 2.11 and below if you are using parallel tuning. But single-node usages are not affected. The incompatibility is because TF 2.12+ will install protobuf 4, and KerasTuner use protobuf 4 to regenerated its grpc files, which is not compatible with protobuf 3 which is used by TF 2.11 and below.

Are you using parallel tuning? @sh-shahrokhi

**Comment by sh-shahrokhi** [comment]
> KerasTuner will not be compatible with TF 2.11 and below if you are using parallel tuning. But single-node usages are not affected. The incompatibility is because TF 2.12+ will install protobuf 4, and KerasTuner use protobuf 4 to regenerated its grpc files, which is not compatible with protobuf 3 which is used by TF 2.11 and below.
> 
> Are you using parallel tuning? @sh-shahrokhi

Thanks for clarification. I do not use parallel tuning. 
I think it would better to remove the limit here on this feedstock. @h-vetinari

**Comment by h-vetinari** [comment]
Thanks for the input @haifeng-jin!

Indeed it's possible that protobuf- or grpc-generated files are not compatible between versions. The important thing here is that we still keep the tensorflow builds separate per given version, and we could do the same for kerastuner (e.g. rebuild for protobuf 3.20 & 3.21), which would then enable the solver to choose one of our compatible tensorflow builds (whether that's 2.9, 2.10, 2.11 etc.)

**Comment by haifeng-jin** [comment]
We have generated grpc files using both protobuf v3 and v4, they will be dynamically loaded based on the situation. So it should be compatible for both TF 2.11 and TF 2.12 now.
https://github.com/keras-team/keras-tuner/pull/898

**Comment by h-vetinari** [comment]
Thanks @haifeng-jin, though this wouldn't have been necessary for conda-forge. In fact, I think it would be better if we do the grpc-generation ourselves, because we often migrate grpc ahead of other packages as well.

We can handle the fact that there would be different kerastuner builds, because we have infrastructure to correctly track dependence on non-python libraries

**Comment by Anselmoo** [comment]
> We have generated grpc files using both protobuf v3 and v4, they will be dynamically loaded based on the situation. So it should be compatible for both TF 2.11 and TF 2.12 now.
> [keras-team/keras-tuner#898](https://github.com/keras-team/keras-tuner/pull/898)

See also: https://github.com/keras-team/keras-tuner/releases/tag/v1.3.5

**Comment by Anselmoo** [comment]
@sh-shahrokhi, based on https://github.com/conda-forge/keras-tuner-feedstock/pull/22#issue-1665830895 can you check it, please?

**Comment by sh-shahrokhi** [comment]
> @sh-shahrokhi, based on [#22 (comment)](https://github.com/conda-forge/keras-tuner-feedstock/pull/22#issue-1665830895) can you check it, please?

Hi, in the 1.3.5 recipe protobuf is limited to 3.20.3
Is this limit necessary?

**Comment by Anselmoo** [comment]
Sorry, no can you make a new PR and remove the limit, please? And increase the Conda recipe version, too.

**Comment by sh-shahrokhi** [comment]
> Sorry, no can you make a new PR and remove the limit, please? And increase the Conda recipe version, too.

done. I increased build number from 0 to 1

**Comment by sh-shahrokhi** [comment]
Would you please merge it? it passed the tests

> Sorry, no can you make a new PR and remove the limit, please? And increase the Conda recipe version, too.

**Comment by sh-shahrokhi** [comment]
it works. thank you

**Comment by Anselmoo** [comment]
> it works. thank you

thank you for figuring It out 👍
